use_frameworks!

platform :ios, '11.0'

target 'XDFastFunc_Example' do
  pod 'XDFastFunc', :path => '../'

  target 'XDFastFunc_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
